---
title: "Ejercicios Sesión 5"
author: "Capacitadores R en DET"
date: "18-12-2020"
output: pdf_document
header-includes:
- \usepackage[fontsize=12pt]{scrextend}
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Objetivo

Desarrollar visualizaciones simples y claras con el paquete `ggplot2`.

## Primer ejercicio

Descargar la base de datos [`WDI INDICATORS  LA.xlsx`](https://github.com/nicolasrattor/sesion_5/raw/master/data/WDI%20INDICATORS%20%20LA.xlsx) y cargarla en el ambiente de R. 


## Segundo ejercicio

¿Cuántas filas y columnas tiene la base de datos?

¿Es práctico el actual formato de la base para trabajar con `ggplot2`?

¿Que modificaciones le harías a la base de datos?

(te recomendamos aplicarle `pivot_longer`)

¿Cuántas filas y columnas tiene la nueva base de datos?


## Tercer ejercicio

¿Cuántos países existen en la base de datos?

Crea una nueva base de datos que solamente contenga datos para un país (el que tú quieras). Dale el nombre del país seleccionado a esta nueva base de datos.

Filtra la base del país, dejando solamente los datos de una variable (`serie`), la que te parezca más interesante y que ojalá no tenga muchos valores perdidos (`NA` o `..`).

Grafica la evolución en el tiempo de la variable que seleccionaste. 


## Cuarto ejercicio

Considerando la misma variable, u otra, y compara la evolución de esta en el tiempo entre 3 o más países. 


## Quinto ejercicio

Filtre la base de datos de todos los países por otra variable y selecciona un año, el que te parezca. 

Haga un gráfico de barras, donde cada barra corresponda a un país. Si gusta, al final del código puede agregar el comando `+ coord_flip()`, para invertir el gráfico y que sea más clara su lectura. 


## Sexto ejercicio

Replique el ejercicio anterior, pero en vez de seleccionar un año, seleccione cuatro años (por ejemplo: 1960,1980,2000 y 2019). Haga un gráfico con 4 paneles, donde cada uno corresponda a un año.

Para mejorar la visualización puede seleccionar algunos países.



